### ISSUE TITLE
Error: "Something went wrong. The container schema was not created. Network error: Response not successful: Received status code 401"

### ISSUE THREAD

**Issue by shabmohd** [commercetools/commercetools-mc-custom-objects-starter#86]
Ran into the below error - "Something went wrong. The container schema was not created. Network error: Response not successful: Received status code 401", while creating the custom object.

PROJECT_KEY and AUTH_TOKEN were set as per the instructions 
$ export PROJECT_KEY={project_key}
$ export AUTH_TOKEN={access_token}

Please let me know if am missing anything here.

**Comment by jluterek** [comment]
This error indicates an issue with authentication.

Are you trying to create a new GraphQL schema file (https://github.com/commercetools/commercetools-mc-custom-objects-starter#generating-graphql-schema) where you need to export those values?

Are you trying to run it locally? In which case you need to ensure the environment variables are set correctly (https://github.com/commercetools/commercetools-mc-custom-objects-starter/blob/master/env.local.json) and you have a valid login to the commercetools Merchant Center.  Please be sure you are connecting to the correct region for your account.

**Comment by shabmohd** [comment]
Thanks @jluterek , I am running the application locally, the issue is resolved now.
